### ISSUE TITLE
Errors--image permissions issue?

### ISSUE THREAD

**Issue by gabrielesh** [aaronpeikert/workflow-showcase#2]
Hi,
This is a great project! When I tried to use your make build command, however, I get several errors. 

The first is less serious as I found a work-around, but I thought I'd let you know. It's an error message that seems to be related either to the fact that I have synced my folders to OneDrive, or to the fact that syncing my folders to OneDrive means that I'm nested in a terrible long filename. The error I get is as follows:

> LIB-ANW0002:workflow-showcase [user redacted]$ make build
> docker build -t OneDrive - University Of Reproducible workflow-showcase .
> invalid argument "OneDrive" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
> See 'docker build --help'.
> make: *** [build] Error 125
I get the same error message whether I am using the default Mac install of make or the latest make installed via brew.

When instead I move the cloned git repo workflow-showcase outside of the OneDrive sync folder I get much further. I'm able to successfully complete  `make build` and go to the next command. However, I then get stuck again trying to access the Docker image. Here is the complete error message: 
> LIB-ANW0002:workflow-showcase [user redacted]$ make all DOCKER=TRUE
> docker run --rm --user --user 567204412 -v /Users/[user redacted]/workflow-showcase:/home/rstudio workflow-showcase Rscript -e 'rmarkdown::render("/home/rstudio/manuscript.Rmd")'
> Unable to find image '567204412:latest' locally
> docker: Error response from daemon: pull access denied for 567204412, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.
> make: *** [manuscript.pdf] Error 125
Any suggestions? Is image 567204412 misnamed somewhere in the code, or does it have a permissions issue?

Many thanks. I really enjoyed your article and would like to reproduce.

**Comment by aaronpeikert** [comment]
Hi gabrielesh,
I am very happy that you are reproducing this :)
The first error stems likely from having spaces in your filename.

I think the second one is related to the [enabling of volumes in windows](https://github.com/aaronpeikert/reproducible-research/blob/2abd93ed4021a496a42a02056968d9c4d98d818c/manuscript.Rmd#L269)

Do you have enabled volume sharing in the settings, like here:
https://docs.docker.com/docker-for-windows/#shared-drives

It is funny on some systems we have tested it on, docker asks you whether or not you want to enable it if you run the command on others not.

Let me know how it goes. If everything is fine, feel free to close this issue, otherwise, do not hesitate to ask again.

**Comment by gabrielesh** [comment]
Hi Aaron,
Thanks so much for this detailed response. I should have clarified that I'm on a Mac OS 10.14.6, not a PC. I've successfully spun up and used Docker containers that have local volumes recently. 

Regardless of platform, it does seem that your "fix double --user flag" commit helped, since after I pulled the new version the container got much farther before quitting. Below is the new error message. It now looks like make is quitting due to a data file mismatch. Do you have any suggestions?

Thanks,
Gabriele

> LIB-ANW0002:workflow-showcase [user redacted]$ make all DOCKER=TRUE
> docker run --rm --user 567204412 -v /Users/[user redacted]/workflow-showcase:/home/rstudio workflow-showcase Rscript -e 'rmarkdown::render("/home/rstudio/manuscript.Rmd")'
> 
> 
> processing file: manuscript.Rmd
>   |.........                                                             |  12%
>   ordinary text without R code
> 
>   |..................                                                    |  25%
> label: setup (with options) 
> List of 1
>  $ include: logi FALSE
> 
>   |..........................                                            |  38%
>   ordinary text without R code
> 
>   |...................................                                   |  50%
> label: unnamed-chunk-1
>   |............................................                          |  62%
>   ordinary text without R code
> 
>   |....................................................                  |  75%
> label: unnamed-chunk-2
> Quitting from lines 23-28 (manuscript.Rmd) 
> Error in error("Mismatch between original and current data file!") : 
>   could not find function "error"
> Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
> 
> Execution halted
> make: *** [manuscript.pdf] Error 1

**Comment by aaronpeikert** [comment]
Hey Gabriele,
thank you for sticking with me with this issue. The digest package changed behaviour since we calculated the hash... I have fixed this issue now.
Thank you so much for pointing me to this issue and investing your time into this.

**Comment by gabrielesh** [comment]
Success! Thanks Aaron
